In [19]:
import numpy as np

def batch_iterator(X, y=None, batch_size=64):
    result = []
    idx = 0
    while(idx < len(X)):
        result.append(X[idx:idx+batch_size])
        if y is not None:
            result.append(y[idx:idx+batch_size])
        idx += batch_size
    return result
    # if y is not None:
    #     return np.array(new_x), np.array(new_y)
    # return np.array(new_x)

X = np.array([[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8], 
                  [9, 10]])
y = np.array([1, 2, 3, 4, 5])
batch_size = 2
batch_iterator(X, y, batch_size)

[array([[1, 2],
        [3, 4]]),
 array([1, 2]),
 array([[5, 6],
        [7, 8]]),
 array([3, 4]),
 array([[ 9, 10]]),
 array([5])]