In [124]:
import numpy as np

def shuffle_data(X, y, seed=None):
	if seed:
		np.random.seed(seed)
	idx = np.arange(X.shape[0])
	np.random.shuffle(idx)
	return X[idx], y[idx]

X = np.array([[1, 2], 
            [3, 4], 
            [5, 6], 
            [7, 8]])
y = np.array([1, 2, 3, 4])
shuffle_data(X, y, seed=42)

(array([[3, 4],
        [7, 8],
        [1, 2],
        [5, 6]]),
 array([2, 4, 1, 3]))

In [113]:
import numpy as np
# Hard mode, avoid using ANY modules, aside from numpy just for data arrays
def shuffle_data(X, y, seed=None):
	if X.shape[0] != y.shape[0]:
		return
	X_shuffled, y_shuffled = np.zeros_like(X), np.zeros_like(y)
	if seed:
		seed = sum([ord(s) for s in seed]) if isinstance(seed, str) else int(seed)
	else:
		new_dic = {}
		seed = id(new_dic)
	feeding_counter = 0
	while X.shape[0] != 0:
		i = seed % X.shape[0]
		X_shuffled[feeding_counter, :] = X[i, :]
		X= np.delete(X, [i], axis=0)
		y_shuffled[feeding_counter] = y[i]
		y = np.delete(y, [i], axis=0)
		feeding_counter += 1
	return X_shuffled, y_shuffled


X = np.array([[1, 2], 
            [3, 4], 
            [5, 6], 
            [7, 8]])
y = np.array([1, 2, 3, 4])
shuffle_data(X, y, seed='steve')

X[0].shape=(2,)
X.size=8
X.size=6
X.size=4
X.size=2


(array([[7, 8],
        [5, 6],
        [3, 4],
        [1, 2]]),
 array([4, 3, 2, 1]))