The Gaussian Elimination method transforms the system of equations into an upper triangular matrix and then uses backward substitution to solve for the variables.

In [6]:
import numpy as np

def gaussian_elimination(A, b):
	"""
	Solves the system Ax = b using Gaussian Elimination with partial pivoting.
    
	:param A: Coefficient matrix
	:param b: Right-hand side vector
	:return: Solution vector x
	"""
	for pidx in range(len(A)-1):
		highest_index = (None, None)
		current_x = current_y = pidx
		for index, values in enumerate(A[current_x:]):
			if highest_index[0] == None or values[current_y] > highest_index[1]:
				highest_index = (index + current_x, values[current_y])
		A[[current_x, highest_index[0]]] = A[[highest_index[0], current_x]]
		b[[current_x, highest_index[0]]] = b[[highest_index[0], current_x]]
		pivot_value = A[current_x][current_y]
		values_to_pivot_upon = A[current_x]
		for index, values in enumerate(A[current_x + 1:]):
			m = values[current_x] / pivot_value
			for i in range(len(values_to_pivot_upon)):
				values[i] -= m * values_to_pivot_upon[i]
			b[index + 1 + current_x] = b[index + 1 + current_x] - m * b[current_x]
			A[index + 1 + current_x] = values

		print(A)
		print(b)


	results = np.zeros_like(b)
	for pidx in range(len(A)):
		current_idx = len(A) - pidx - 1
		a_row = A[current_idx]
		b_val = b[current_idx]
		numerator = b_val - sum(results[current_idx:] * a_row[current_idx:])
		results[current_idx] = numerator / a_row[current_idx]

	return results

A = np.array([[2,8,4], [2,5,1], [4,10,-1]], dtype=float)
b = np.array([2,5,1], dtype=float)

print(gaussian_elimination(A, b)) # [11.0, -4.0, 3.0]

[[ 4.  10.  -1. ]
 [ 0.   0.   1.5]
 [ 0.   3.   4.5]]
[1.  4.5 1.5]
[[ 4.  10.  -1. ]
 [ 0.   3.   4.5]
 [ 0.   0.   1.5]]
[1.  1.5 4.5]
[11. -4.  3.]


In [7]:
A = np.array([
    [0, 2, 1, 0, 0, 0, 0],
    [2, 6, 2, 1, 0, 0, 0],
    [1, 2, 7, 2, 1, 0, 0],
    [0, 1, 2, 8, 2, 1, 0],
    [0, 0, 1, 2, 9, 2, 1],
    [0, 0, 0, 1, 2, 10, 2],
    [0, 0, 0, 0, 1, 2, 11]
], dtype=float)
b = np.array([1, 2, 3, 4, 5, 6, 7], dtype=float)
print(gaussian_elimination(A, b))

[[ 2.   6.   2.   1.   0.   0.   0. ]
 [ 0.   2.   1.   0.   0.   0.   0. ]
 [ 0.  -1.   6.   1.5  1.   0.   0. ]
 [ 0.   1.   2.   8.   2.   1.   0. ]
 [ 0.   0.   1.   2.   9.   2.   1. ]
 [ 0.   0.   0.   1.   2.  10.   2. ]
 [ 0.   0.   0.   0.   1.   2.  11. ]]
[2. 1. 2. 4. 5. 6. 7.]
[[ 2.   6.   2.   1.   0.   0.   0. ]
 [ 0.   2.   1.   0.   0.   0.   0. ]
 [ 0.   0.   6.5  1.5  1.   0.   0. ]
 [ 0.   0.   1.5  8.   2.   1.   0. ]
 [ 0.   0.   1.   2.   9.   2.   1. ]
 [ 0.   0.   0.   1.   2.  10.   2. ]
 [ 0.   0.   0.   0.   1.   2.  11. ]]
[2.  1.  2.5 3.5 5.  6.  7. ]
[[ 2.          6.          2.          1.          0.          0.
   0.        ]
 [ 0.          2.          1.          0.          0.          0.
   0.        ]
 [ 0.          0.          6.5         1.5         1.          0.
   0.        ]
 [ 0.          0.          0.          7.65384615  1.76923077  1.
   0.        ]
 [ 0.          0.          0.          1.76923077  8.84615385  2.
   1.        ]
 [ 0.   

In [4]:
highest_index = (None, None)
current_x = 0
current_y = 0
for index, values in enumerate(A[current_x:]):
    if highest_index[current_y] == None or values[current_y] > highest_index[1]:
        highest_index = (index, values[0])
A[[current_x, highest_index[0]]] = A[[highest_index[0], current_x]]
A

array([[ 4., 10., -1.],
       [ 2.,  5.,  1.],
       [ 2.,  8.,  4.]])

In [5]:
b[[current_x, highest_index[0]]] = b[[highest_index[0], current_x]]
b

array([1., 5., 2.])

In [6]:
current_x

0

In [7]:
pivot_value = A[current_x][current_y]
pivot_value

np.float64(4.0)

In [8]:
values_to_pivot_upon = A[current_x]
for index, values in enumerate(A[current_x + 1:]):
    m = values[current_x] / pivot_value
    for i in range(len(values_to_pivot_upon)):
        values[i] -= m * values_to_pivot_upon[i]
    b[index + 1] = b[index + 1] - m * b[current_x]
    A[index + 1] = values
print(A)
print(b)

[[ 4.  10.  -1. ]
 [ 0.   0.   1.5]
 [ 0.   3.   4.5]]
[1.  4.5 1.5]
