In [ ]:
import numpy as np

def rref(matrix):
    matrix = matrix.astype(float)
    for col_num in range(len(matrix[0])):
        for row_num in range(col_num, len(matrix)):
            if matrix[row_num, col_num] != 0:
                matrix[[col_num, row_num]] = matrix[[row_num, col_num]]
                row_num = col_num
                matrix[row_num] = matrix[row_num] / matrix[row_num][col_num]
                for row_num_2 in range(len(matrix)):
                    if row_num != row_num_2 and matrix[row_num_2, col_num] != 0:
                        while matrix[row_num_2, col_num] != 0:
                            if matrix[row_num_2, col_num]>0:
                                matrix[row_num_2] = matrix[row_num_2] - (matrix[row_num] * matrix[row_num_2, col_num])
                            else: 
                                matrix[row_num_2] = matrix[row_num_2] + (matrix[row_num] * matrix[row_num, col_num])
                break

    return matrix


matrix = np.array([
    [1, 2, -1, -4],
    [2, 3, -1, -11],
    [-2, 0, -3, 22]
])

rref_matrix = rref(matrix)
print(rref_matrix)

[[ 1.  0.  0. -8.]
 [-0.  1.  0.  1.]
 [-0. -0.  1. -2.]]


In [36]:
matrix = np.array([
    [0, 2, -1, -4],
    [2, 0, -1, -11],
    [-2, 0, 0, 22]
])

output = rref(matrix)
print(output)

KeyboardInterrupt: 