## Standard Method

In [8]:
from math import sqrt
import numpy as np 
def svd_2x2_singular_values(A: np.ndarray) -> tuple: 
    # Get A^TA
    AT_A = np.matmul(A.T, A)
    # get eigenvalues and V of A^TA
    (eigenvalues, V) = np.linalg.eig(AT_A)
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    V = V[:, sorted_indices]
    eigenvalues = np.clip(eigenvalues, 0, None)
    
    # Ensure eigenvalues are non-negative
    eigenvalues = np.clip(eigenvalues, 0, None)
    # Form sigma
    sigma = np.array([[sqrt(eigenvalues[0]), 0], [0, sqrt(eigenvalues[1])]])

    # Now to calculate U
    U = np.zeros_like(V)

    # # We're gonna cheat as U = AVE^-1
    # sigma_inv = np.linalg.inv(sigma)
    # v_sig_inv = V @ sigma_inv
    # U = A @ v_sig_inv

    # The above works, let's try this...
    # A way to loop through the columns
    for i in [0, 1]:
        top = np.matmul(A, V.T[i])
        sigma_val = sigma.diagonal()[i]
        U.T[i] = np.divide(top, sigma_val)

    # The only what diags for sigma
    return U, sigma.diagonal(), V.T

A = np.array([[1, 1], [-1, 1]])
print(f"Original: \n {A}")
svd_2x2_singular_values(A)

Original: 
 [[ 1  1]
 [-1  1]]


(array([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]]),
 array([1.41421356, 1.41421356]),
 array([[0., 1.],
        [1., 0.]]))

In [ ]:
A = np.array([[2, 1], [1, 2]])
svd_2x2_singular_values(A)

In [11]:
U,s,V = svd_2x2_singular_values(np.array([[-10, 8], [10, -1]]))
result = U @ np.diag(s) @ V
print(result)

[[-10.   8.]
 [ 10.  -1.]]


In [10]:
A = np.array([[1, 2], [3, 4]])
U,s,V = svd_2x2_singular_values(A)

U @ np.diag(s) @ V

array([[1., 2.],
       [3., 4.]])

## Jacobi Method

In [ ]:
from math import sqrt
import numpy as np 
def svd_2x2_singular_values(A: np.ndarray) -> tuple: 
    # Get A^TA
    AT_A = np.matmul(A.T, A)
    theta = 0.5*np.arctan2(2*AT_A[0][1], AT_A[0][0]-AT_A[1][1])
    P = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    
    A_prime = np.matmul(P.T, np.matmul(AT_A, P))

    # Calculate first parts
    sigma = np.array([[sqrt(A_prime[0, 0]), 0], [0, sqrt(A_prime[1, 1])]])
    V = P

    sigma_inverted = np.linalg.inv(sigma)
    U = np.matmul(A, np.matmul(V, sigma_inverted))

    return U, sigma.diagonal(), V.T

A = np.array([[1, 1], [-1, 1]])
svd_2x2_singular_values(A)

In [ ]:
A = np.array([[1, 2], [3, 4]])
svd_2x2_singular_values(A)

In [ ]:
results = np.linalg.svd(np.array([[1, 2], [3, 4]]))
print(results[0])
print(results[1])
print(results[2])

In [74]:
import numpy as np 

def svd_2x2_singular_values(A: np.ndarray) -> tuple: 
    # Stage 1: Find V
    # Get A^T * A
    AT_A = A.T @ A
    # Set V to identity matrix 2x2
    V = np.identity(2)
    U = np.identity(2)
    # Find the rotation matrix J
    theta = 0.5 * np.arctan2(2 * AT_A[0, 1], AT_A[0, 0] - AT_A[1, 1])
    J = np.array([[np.cos(theta), -np.sin(theta)],
                [np.sin(theta), np.cos(theta)]])
    # Find the new AT_A via J^T * AT_A * J
    AT_A = J.T @ AT_A @ J
    # V = VJ
    V = V @ J
    # U = UJ
    U = U @ J

    return U, np.sqrt(np.diag(AT_A)), V.T

    

svd_2x2_singular_values(np.array([[1, -1], [1, 1]]))

(array([[1., 0.],
        [0., 1.]]),
 array([1.41421356, 1.41421356]),
 array([[1., 0.],
        [0., 1.]]))

In [58]:
svd_2x2_singular_values(np.array([[4, 2], [1, 3]]))

(array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]),
 array([5.11667274, 1.95439508]),
 array([[ 0.76775173,  0.64074744],
        [-0.64074744,  0.76775173]]))

In [75]:
svd_2x2_singular_values(np.array([[1, 2], [3, 4]]))

(array([[ 0.57604844, -0.81741556],
        [ 0.81741556,  0.57604844]]),
 array([5.4649857 , 0.36596619]),
 array([[ 0.57604844,  0.81741556],
        [-0.81741556,  0.57604844]]))

In [70]:
import numpy as np

def svd_2x2_singular_values(A: np.ndarray) -> tuple:
    # Stage 1: Find V
    AT_A = A.T @ A
    theta = 0.5 * np.arctan2(2 * AT_A[0, 1], AT_A[0, 0] - AT_A[1, 1])
    J = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta), np.cos(theta)]])
    V = np.identity(2) @ J
    U = np.identity(2) @ J
    
    # Stage 2: Find singular values
    AT_A_diag = J.T @ AT_A @ J
    singular_values = np.sqrt(np.diag(AT_A_diag))


    # Return the full matrices U, singular values, and V.T
    return U, singular_values, V.T

# Test the function
U, singular_values, V_T = svd_2x2_singular_values(np.array([[1, 2], [3, 4]]))
print("U:", U)
print("Singular Values:", singular_values)
print("V^T:", V_T)


U: [[ 0.57604844 -0.81741556]
 [ 0.81741556  0.57604844]]
Singular Values: [5.4649857  0.36596619]
V^T: [[ 0.57604844  0.81741556]
 [-0.81741556  0.57604844]]
